### ISSUE TITLE
Add "Restore Labels" column

### ISSUE THREAD

**Issue by marabuuu** [loicsauteur/napari-annotator#2]
Hi @loicsauteur ,

Thanks for this cool napari-plugin! I have a little feature request: 
Now, if you choose to `Erase` a label, it will be deleted, but it is still part of the Label List which can be confusing. Would it be possible to add a `Restore` Label column to get the Label back? 

Best,
Mara

**Comment by loicsauteur** [comment]
Hi @marabuuu 
Thanks for the feature request. It is true, after erasing a label, it remains in the list. 
I am not sure how to implement a `Restore` function yet, but I will look into it when time allows. 
Thanks!

**Comment by loicsauteur** [comment]
Hi @marabuuu 

The `Restore` function is implemented.
Available via pip with the new version (and hopefully soon via conda too).

Please be aware that the restore function is reset as soon as you switch layers.
If you draw new pixels for a label that you erased, restoring the label will keep the newly drawn pixels and add what was drawn before the erase button was pressed.

Thanks again for the feature request!
